name: am-i-up-to-date

on:
  push:
  workflow_dispatch:
    inputs:
      ref:
        description: branch|tag|SHA to checkout
        default: 'main'
        required: true
  schedule:
    # everyday at 02:00 AM JST (UTC+9)
    - cron:  '0 17 * * *'

jobs:
  validate-freshness:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: make check-new-releases check-known-checksums
        shell: bash
